spring.application.name=lab

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate

jwt.secret.access=${JWT_ACCESS_SECRET}
jwt.secret.access.expiration=${JWT_ACCESS_EXPIRATION}

jwt.secret.refresh=${JWT_REFRESH_SECRET}
jwt.secret.refresh.expiration=${JWT_REFRESH_EXPIRATION}

jwt.oauth.client.id=${CLIENT_ID}
jwt.oauth.client.secret=${CLIENT_SECRET}
jwt.oauth.callback_url=${CALLBACK_URL}
app.frontend.oauth-success-url=${OAUTH_SUCCESS}